apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"  # for GKE
spec:
  rules:
  - host: java-gke.YOUR_DOMAIN.com     # optional, or remove for IP-based access
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-gke-app
            port:
              number: 8080
